function buildTestbench(modelName)
% buildTestbench  Costruisce programmaticamente AncTestbench.slx.
%
% Cabla:
%   anc.SourceGeneratorSystem  -> x(n) a 48 kHz
%   anc.FxLMSSystem            -> [y, e_log]
%   FIR Decimator 48k -> 4k    -> x_dec, y_dec
%   anc.FDTD3DSystem           -> [P, p_err]
%   anc.Field3DSink            -> rendering slice
%   Spectrum Analyzer su e_log
%   To Workspace per logging
%
% Il modello si chiama 'AncTestbench' di default.

    if nargin < 1, modelName = 'AncTestbench'; end

    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    if exist([modelName '.slx'], 'file')
        delete([modelName '.slx']);
    end

    new_system(modelName);
    open_system(modelName);

    Fs_audio = 48000;
    Fs_field = 4000;
    Tsim = 5;

    set_param(modelName, ...
        'SolverType', 'Fixed-step', ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', num2str(1/Fs_audio), ...
        'StopTime', num2str(Tsim));

    src = add_block('simulink/User-Defined Functions/MATLAB System', ...
        [modelName '/Source'], ...
        'System', 'anc.SourceGeneratorSystem', ...
        'Position', [40 50 160 110]);
    set_param(src, 'SourceType', '''PinkNoise''', ...
        'SampleRate', num2str(Fs_audio), ...
        'Duration', '10', 'Amplitude', '0.5');

    fxlms = add_block('simulink/User-Defined Functions/MATLAB System', ...
        [modelName '/FxLMS'], ...
        'System', 'anc.FxLMSSystem', ...
        'Position', [260 40 380 120]);
    set_param(fxlms, 'Lw', '512', ...
        'SecondaryPath', 's_est', ...
        'StepSize', '5e-3', 'Epsilon', '1e-2');

    err_sum = add_block('simulink/Math Operations/Sum', ...
        [modelName '/ErrorSum'], 'Position', [460 60 490 90], ...
        'Inputs', '+-');

    dec_x = add_block('dsp/Filtering/Multirate Filters/FIR Decimation', ...
        [modelName '/DecimX'], 'Position', [260 160 380 220]);
    set_param(dec_x, 'M', num2str(Fs_audio/Fs_field));

    dec_y = add_block('dsp/Filtering/Multirate Filters/FIR Decimation', ...
        [modelName '/DecimY'], 'Position', [260 260 380 320]);
    set_param(dec_y, 'M', num2str(Fs_audio/Fs_field));

    fdtd = add_block('simulink/User-Defined Functions/MATLAB System', ...
        [modelName '/FDTD3D'], ...
        'System', 'anc.FDTD3DSystem', ...
        'Position', [460 180 600 300]);
    set_param(fdtd, ...
        'RoomSize', '[6 6 3]', 'Dx', '0.2', ...
        'FieldSampleRate', num2str(Fs_field), ...
        'SourcePos', '[1.0 3.0 1.5]', ...
        'AncPos', '[4.0 3.0 1.5]', ...
        'ErrorMicPos', '[5.0 3.0 1.5]', ...
        'BoundaryType', '''Mur''');

    sink = add_block('simulink/User-Defined Functions/MATLAB System', ...
        [modelName '/Field3DSink'], ...
        'System', 'anc.Field3DSink', ...
        'Position', [680 180 820 260]);
    set_param(sink, 'SlicePlane', '''XY''', 'SliceIndex', '8', ...
        'RefreshDecim', '20', 'ColorLimit', '0.05', ...
        'RoomSize', '[6 6 3]', 'Dx', '0.2', ...
        'SourcePos', '[1.0 3.0 1.5]', ...
        'AncPos', '[4.0 3.0 1.5]', ...
        'ErrorMicPos', '[5.0 3.0 1.5]');

    scope_e = add_block('simulink/Sinks/Scope', ...
        [modelName '/ErrorScope'], 'Position', [680 40 760 90]);

    to_ws_e = add_block('simulink/Sinks/To Workspace', ...
        [modelName '/e_log'], 'Position', [680 110 760 150], ...
        'VariableName', 'e_log', 'SaveFormat', 'Timeseries');

    spec = add_block('dsp/Sinks/Spectrum Analyzer', ...
        [modelName '/Spectrum'], 'Position', [800 60 880 110]);

    add_line(modelName, 'Source/1', 'FxLMS/1', 'autorouting', 'on');
    add_line(modelName, 'ErrorSum/1', 'FxLMS/2', 'autorouting', 'on');
    add_line(modelName, 'Source/1', 'ErrorSum/1', 'autorouting', 'on');
    add_line(modelName, 'FxLMS/1', 'ErrorSum/2', 'autorouting', 'on');
    add_line(modelName, 'FxLMS/2', 'ErrorScope/1', 'autorouting', 'on');
    add_line(modelName, 'FxLMS/2', 'e_log/1', 'autorouting', 'on');
    add_line(modelName, 'FxLMS/2', 'Spectrum/1', 'autorouting', 'on');

    add_line(modelName, 'Source/1', 'DecimX/1', 'autorouting', 'on');
    add_line(modelName, 'FxLMS/1', 'DecimY/1', 'autorouting', 'on');
    add_line(modelName, 'DecimX/1', 'FDTD3D/1', 'autorouting', 'on');
    add_line(modelName, 'DecimY/1', 'FDTD3D/2', 'autorouting', 'on');
    add_line(modelName, 'FDTD3D/1', 'Field3DSink/1', 'autorouting', 'on');

    save_system(modelName);
    fprintf('Modello salvato: %s.slx\n', modelName);
end
